--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Debian 17.4-1.pgdg120+2)
-- Dumped by pg_dump version 17.4 (Debian 17.4-1.pgdg120+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: dbuser
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO dbuser;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: dbuser
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: loan; Type: TABLE; Schema: public; Owner: dbuser
--

CREATE TABLE public.loan (
    id integer NOT NULL,
    enddate date NOT NULL,
    returneddate date,
    startdate date NOT NULL,
    mediaid integer NOT NULL,
    userid integer NOT NULL
);


ALTER TABLE public.loan OWNER TO dbuser;

--
-- Name: loan_id_seq; Type: SEQUENCE; Schema: public; Owner: dbuser
--

ALTER TABLE public.loan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.loan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: media; Type: TABLE; Schema: public; Owner: dbuser
--

CREATE TABLE public.media (
    id integer NOT NULL,
    author character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    genre character varying(255) NOT NULL,
    imageurl character varying(255),
    isrented boolean DEFAULT false NOT NULL,
    isbn character varying(255) NOT NULL,
    mediatype character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    CONSTRAINT media_mediatype_check CHECK (((mediatype)::text = ANY ((ARRAY['BOOK'::character varying, 'MAGAZINE'::character varying, 'MOVIE'::character varying, 'CD'::character varying])::text[])))
);


ALTER TABLE public.media OWNER TO dbuser;

--
-- Name: media_id_seq; Type: SEQUENCE; Schema: public; Owner: dbuser
--

ALTER TABLE public.media ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: useraccount; Type: TABLE; Schema: public; Owner: dbuser
--

CREATE TABLE public.useraccount (
    id integer NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    usertype character varying(255) NOT NULL,
    CONSTRAINT useraccount_usertype_check CHECK (((usertype)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);


ALTER TABLE public.useraccount OWNER TO dbuser;

--
-- Name: useraccount_id_seq; Type: SEQUENCE; Schema: public; Owner: dbuser
--

ALTER TABLE public.useraccount ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.useraccount_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: loan; Type: TABLE DATA; Schema: public; Owner: dbuser
--

COPY public.loan (id, enddate, returneddate, startdate, mediaid, userid) FROM stdin;
\.


--
-- Data for Name: media; Type: TABLE DATA; Schema: public; Owner: dbuser
--

COPY public.media (id, author, description, genre, imageurl, isrented, isbn, mediatype, title) FROM stdin;
1	Beatles	Denna CD innehåller 38 låtar, varav 30 har nya mixar från 2023. Med texter av John Harris är "1962–1966" en hyllning till The Beatles och deras tidlösa musik för både gamla och nya fans.	Mix	cd-1962-1966.jpg	f	12422	CD	1962-1966
2	Beatles	Denna CD innehåller 37 låtar, varav 6 har nya mixar från 2023. Med texter av John Harris är "1966–1970" en hyllning till The Beatles och deras tidlösa musik för både gamla och nya fans.	Mix	cd-1967-1970.jpg	f	12433	CD	1967-1970
3	Rolling Stones	Rolling Stones fortsätter att dominera musikvärlden. "Honk" samlar 36 hits från "Sticky Fingers" (1971) och framåt, inklusive "Start Me Up", "Angie" och "Miss You". De intar än idag topplistor och scenen med sin ikoniska stil.	Rock	cd-honk.jpg	f	553398	CD	Honk
4	SVT	Alla 30 bidrag från Melodifestivalen 2025!	Mix	cd-melodifestivalen.jpg	f	30941	CD	Melodifestivalen
5	Per Gessle	Sällskapsjuk är inspelat i Halmstad och som titeln signalerar, består albumet till största delen av duetter med en rad starkt lysande sångare.	Mix	cd-sallskapssjuk.jpg	f	55431	CD	Sällskapssjuk
6	ABBA	ABBA släpper "The Singles - The First Fifty Years", en utökad version av 1982 års samling. Albumet innehåller 38 låtar, inklusive hits och unika spår, samt singlar från deras senaste album "Voyage".	Mix	cd-the-singles.jpg	f	30057	CD	The singles
7	Michael Mann	Rånledaren Neil McCauley planerar en stor stöt, medan polisen Vincent Hanna är fast besluten att stoppa honom. Snart är de på kollisionskurs, och en oundviklig uppgörelse väntar.	Action	movie-heat.jpg	f	410832	MOVIE	Heat
8	Christopher Nolan	"Oppenheimer" skildrar fysikern J. Robert Oppenheimer, hjärnan bakom atombomben. Filmen följer hans briljans, moraliska dilemman och effekterna av hans skapelse, från Manhattanprojektet till efterkrigstidens politiska konsekvenser.	Thriller	movie-oppenheimer.jpg	f	15471	MOVIE	Oppenheimer
9	Steven Spielberg	När en dödlig vithaj terroriserar en badort, tvingas polischefen, en marinbiolog och en hajjägare samarbeta för att stoppa monstret innan fler liv går förlorade. En kamp mellan människa och natur tar sin början.	Skräck	movie-jaws.jpg	f	404945	MOVIE	Jaws
10	Steven Spielberg	En vilsen utomjording och en ensam pojke blir vänner i ett tidlöst äventyr. Tillsammans kämpar de för att få E.T. hem igen, medan myndigheterna jagar dem. En magisk berättelse om vänskap utan gränser.	Barn	movie-e.t.jpg	f	329070	MOVIE	E.T.
11	Paul King	Paddington anländer till London för att hitta ett nytt hem och en gammal upptäcktsresande. På stationen hittar familjen Brown honom med en lapp: "Var snäll och ta hand om den här björnen" – och deras liv förändras för alltid.	Barn	movie-paddington.jpg	f	336274	MOVIE	Paddington
12	Richard Linklater	Gary, en universitetslärare och falsk yrkesmördare, förälskar sig i Maddy, som är intresserad av hans hemliga alter ego. Hans dubbelliv blir komplicerat när han försöker hålla masken.	Komedi	movie-hitman.jpg	f	18697	MOVIE	Hit Man
13	Aller Media	Vill du veta vad som händer i kändisvärlden? Här är tidningen som inte är rädd för att vara lite närgången. Läs om vad våra kära kungligheter, kändisar och stjärnor har för sig.	Skvaller	magazine-hant-extra.jpg	f	Hant-Extra-2-2025	MAGAZINE	Hänt Extra
14	Story House Egmont	Kalle Anka är en av Sveriges mest populära barn serietidningar som ger dig oslagbar underhållning varje vecka! Häng med Kalle Anka och hans vänner på alla äventyr och mycket där till..	Serietidning	magazine-kalle-anka.jpg	f	Kalle-Anka-2-2025	MAGAZINE	Kalle Anka
15	Story House Egmont	Tidningen GOAL är fotbollsmagasinet som tar läsaren till de största ligorna, de bästa matcherna och de mest glimrande stjärnorna.	Sport	magazine-goal.jpg	f	Goal-2-2025	MAGAZINE	Goal
16	Martin Widmark	En astronaut besöker Valleby och väljer ut Barbro Palm för en rymdresa. Men något verkar konstigt, och LasseMajas detektivbyrå undersöker vad astronauten egentligen har i kikaren.	Barn	book-rymdmysteriet.jpg	f	808034	BOOK	Rymdmysteriet
17	Sven Nordqvist	Pettson är på dåligt humör en grå höstdag, men Findus försöker få honom på bättre humör genom att föreslå fiske. Det krävs många idéer för att få Pettson ut, men till slut mår han bra på sjön.	Barn	book-stackars-pettson.jpg	f	623582	BOOK	Stackars Pettson
18	Steve Smallman	Bonden Blom är väldigt uppspelt när han får sin nya fyrhjuling. Den är bättre än en traktor! Men kan den dra loss faster Frejas bil ur ett lerigt hål? Som vanligt får bonden Blom en idé.	Barn	book-traktorhjalten.jpg	f	729868	BOOK	Traktorhjälten
19	Mary Kubica	Shelby Tebow försvinner, och kort därefter försvinner Meredith och hennes dotter Delilah. Efter 11 år återvänder Delilah, och när sanningen om vad som hänt avslöjas, vänds allt upp och ner.	Deckare	book-kvinna-saknad.jpg	f	856623	BOOK	Kvinna Saknad
20	David Baldacci	Efter ett mordförsök får Travis Devine i uppdrag att skydda tolvåriga Betsy, vars föräldrar dog mystiskt. Uppdraget utvecklas till en dödlig sammansvärjning som testar hans lojalitet.	Deckare	book-skyddsangeln.jpg	f	807196	BOOK	Skyddsängeln
21	Hans Rosenfeldt	Hannah Wester, Haparandapolisen, konfronteras med en död varg, en blodig knarkuppgörelse och en kvinnlig lönnmördare. När spåren leder till Finland, upptäcker hon en dödlig sammansvärjning.	Deckare	book-vargasommar.jpg	f	754332	BOOK	Vargasommar
22	J.R.R. Tolkien	Silmarillion berättar om skapelsen av världen, silmarillerna och kriget med den onde Morgoth. Det är en förhistoria till Sagan om ringen med magiska varelser och gudar.	Fantasy	book-silmarillion.jpg	f	702192	BOOK	Silmarillion
23	Gregory Maguire	Wicked berättar om Elphaba, den gröna häxan från Oz, och hennes kamp för att skydda de talande djuren från den orättvisa makten. En historia om makt, förtryck, vänskap och moral i en magisk värld.	Fantasy	book-wicked.jpg	f	853788	BOOK	Wicked
24	Lucinda Riley	CeCe, en konstnär som känner sig vilsen efter faderns död, får ledtrådar som leder henne till Australien. Där upptäcker hon en koppling till skotska Kitty McBride och söker sina rötter.	Roman	book-parlsystern.jpg	f	741004	BOOK	Pärlsystern
25	Rebecca Yarros	"Iron Flame" av Rebecca Yarros handlar om en ung kvinna som kämpar för att överleva i en tuff värld fylld av förluster, hemligheter och farliga beslut, samtidigt som hon navigerar komplexa relationer och utmaningar.	Fantasy	book-iron-flame.jpg	f	780079	BOOK	Iron Flame
26	Katarina Widholm	Betty, som förlorat sin man Olof för fyra år sedan, plågas av skuld och förlorade möjligheter. Med barnen Martina och Anders söker hon nu efter en väg att följa sina känslor och bli älskad igen.	Roman	book-alskade-betty.jpg	f	848345	BOOK	Älskade Betty
27	Moa Herngren	Bea och Niklas har ett långt äktenskap, men efter ett gräl försvinner Niklas hemifrån. När Bea upptäcker att han träffat en annan och vill skiljas, ställs deras relation på sin spets.	Roman	book-skilsmassan.jpg	f	767671	BOOK	Skilsmässan
\.


--
-- Data for Name: useraccount; Type: TABLE DATA; Schema: public; Owner: dbuser
--

COPY public.useraccount (id, email, name, password, usertype) FROM stdin;
1	admin@fulkoping.se	Admin	808a5ce29afe56637fec399c57e0de3ce7f8f2d892537bc1173d9342bac8e56cf29277dedbc0adf605d47c8c161e730a	ADMIN
2	user@fulkoping.se	User	54f0b730cf74280103cb99a93c8e629a35c3a13c82cbff03a00c00d0fe7cab052440d272a691986a9e01a7333cc5369c	USER
\.


--
-- Name: loan_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dbuser
--

SELECT pg_catalog.setval('public.loan_id_seq', 1, false);


--
-- Name: media_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dbuser
--

SELECT pg_catalog.setval('public.media_id_seq', 27, true);


--
-- Name: useraccount_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dbuser
--

SELECT pg_catalog.setval('public.useraccount_id_seq', 2, true);


--
-- Name: loan loan_pkey; Type: CONSTRAINT; Schema: public; Owner: dbuser
--

ALTER TABLE ONLY public.loan
    ADD CONSTRAINT loan_pkey PRIMARY KEY (id);


--
-- Name: media media_pkey; Type: CONSTRAINT; Schema: public; Owner: dbuser
--

ALTER TABLE ONLY public.media
    ADD CONSTRAINT media_pkey PRIMARY KEY (id);


--
-- Name: useraccount ukhqo0emx3b1cgbtl1aany7lugc; Type: CONSTRAINT; Schema: public; Owner: dbuser
--

ALTER TABLE ONLY public.useraccount
    ADD CONSTRAINT ukhqo0emx3b1cgbtl1aany7lugc UNIQUE (email);


--
-- Name: useraccount useraccount_pkey; Type: CONSTRAINT; Schema: public; Owner: dbuser
--

ALTER TABLE ONLY public.useraccount
    ADD CONSTRAINT useraccount_pkey PRIMARY KEY (id);


--
-- Name: loan fksbgj0snymx1ymilb2i6k5uex2; Type: FK CONSTRAINT; Schema: public; Owner: dbuser
--

ALTER TABLE ONLY public.loan
    ADD CONSTRAINT fksbgj0snymx1ymilb2i6k5uex2 FOREIGN KEY (userid) REFERENCES public.useraccount(id);


--
-- Name: loan fkssc9lbj7j4nru0v1al589r7gs; Type: FK CONSTRAINT; Schema: public; Owner: dbuser
--

ALTER TABLE ONLY public.loan
    ADD CONSTRAINT fkssc9lbj7j4nru0v1al589r7gs FOREIGN KEY (mediaid) REFERENCES public.media(id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: dbuser
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


--
-- PostgreSQL database dump complete
--

